services:
  gmail-sorter:
    build: .
    pull_policy: build

    volumes:
      - /opt/gmail-sort-agent/credentials.json:/app/credentials.json:ro
      - /opt/gmail-sort-agent/token.json:/app/token.json
      - /opt/gmail-sort-agent/.env:/app/.env:ro