services:
  gmail-sorter:
    build: .
    pull_policy: build
    profiles: ["build-only"]
    volumes:
      - /opt/gmail-sort-agent/credentials.json:/app/credentials.json:ro
      - /opt/gmail-sort-agent/token.json:/app/token.json
      - /opt/gmail-sort-agent/.env:/app/.env:ro

  scheduler:
    image: mcuadros/ofelia:latest
    command: daemon --docker
    environment:
      - TZ=Europe/Berlin

    labels:
      ofelia.job-run.gmail-sort.schedule: "0 28 23 * * *"
      ofelia.job-run.gmail-sort.image: "gmail-sort-agent-gmail-sorter:latest"
      ofelia.job-run.gmail-sort.delete: "true"
      ofelia.job-run.gmail-sort.volume: '["/opt/gmail-sort-agent/credentials.json:/app/credentials.json:ro","/opt/gmail-sort-agent/token.json:/app/token.json","/opt/gmail-sort-agent/.env:/app/.env:ro"]'

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro